volumes:
  database_data:
networks:
  me2gift_internal:
services:
  backend:
    image: me2gift/backend
    container_name: me2gift
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - me2gift_internal
  dev:
    image: me2gift/backend
    container_name: me2gift-dev
    build: .
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - me2gift_internal
    volumes:
      - .:/tmp/me2gift
    entrypoint: ['/bin/bash']
  database:
    image: postgres:16
    container_name: me2gift-database
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - me2gift_internal
