volumes:
  database_data:
services:
  backend:
    image: me2gift/backend
    container_name: me2gift
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      - NODE_ENV=development
  dev:
    image: me2gift/backend
    container_name: me2gift-dev
    build: .
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - database
    volumes:
      - .:/tmp/me2gift
    environment:
      - NODE_ENV=development
    entrypoint: ['/bin/bash']
  database:
    image: postgres:16
    container_name: me2gift-database
    environment:
      POSTGRES_DB: me2gift
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
